trigger:
- main

jobs:
- job: 'build'
  displayName: 'build-app'
  continueOnError: false
  pool:
    name: 'Runner-01'
  steps:
  - script: |
      wget https://raw.githubusercontent.com/bibichannel/greenblue-deployment/main/backend/Dockerfile
      wget https://github.com/bibichannel/greenblue-deployment/blob/main/backend/entrypoint.sh

  - script: |
      ls -la
      echo "Build.ArtifactStagingDirectory -> $(Build.ArtifactStagingDirectory)"
      echo "Build.BinariesDirectory -> $(Build.BinariesDirectory)"
      echo "Build.SourcesDirectory -> $(Build.SourcesDirectory)"
      echo "pwd -> $(pwd)"
    displayName: 'Install dependencies'

  - script: |
      docker build -t backend-dev:latest --build-arg="STAGE=development" --build-arg="PORT=4000" .
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      ArtifactName: 'sentMail.zip'
      publishLocation: 'Container'