trigger:
- master

jobs:
- job: 'build'
  displayName: 'build-app'
  continueOnError: false
  pool:
    name: 'Runner-01'
  steps:
  - script: |
      wget https://raw.githubusercontent.com/bibichannel/greenblue-deployment/main/backend/Dockerfile
      wget https://raw.githubusercontent.com/bibichannel/greenblue-deployment/main/backend/entrypoint.sh
    displayName: 'Get necessary files on github repository'

  - script: |
      docker build -t backend-dev:latest --build-arg="STAGE=development" --build-arg="PORT=4000" .
      echo "success"
    displayName: 'Build image'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      ArtifactName: 'sentMail-be-dev.zip'
      publishLocation: 'Container'